/* eslint-disable @typescript-eslint/no-explicit-any */
import React from 'react';
import { render, screen } from '@testing-library/react';
import { NextIntlClientProvider } from 'next-intl';

const mockPush = jest.fn();
const mockUseDashboards = jest.fn();

jest.mock('@/hooks/useDashboards', () => ({
  useDashboards: () => mockUseDashboards(),
}));

jest.mock('next/navigation', () => ({
  useRouter: () => ({ push: mockPush }),
}));

jest.mock('@/i18n/navigation', () => ({
  useRouter: jest.fn(() => ({ push: mockPush })),
  Link: ({ children, href }: { children: React.ReactNode; href: string }) => (
    <a href={href}>{children}</a>
  ),
}));

jest.mock('focus-trap-react', () => {
  return ({ children }: { children: React.ReactNode }) => <>{children}</>;
});

jest.mock('lucide-react', () => ({
  Plus: () => <span data-testid="icon-plus">+</span>,
  LayoutDashboard: () => <span data-testid="icon-dashboard">D</span>,
  Pencil: () => <span data-testid="icon-pencil">E</span>,
  Trash2: () => <span data-testid="icon-trash">X</span>,
  Calendar: () => <span data-testid="icon-calendar">C</span>,
  Loader2: ({ className }: any) => <div data-testid="loader" className={className} role="status" />,
  Copy: () => <span data-testid="icon-copy">CP</span>,
}));

const messages = {
  dashboard: {
    title: 'Dashboards',
    count: '{count} dashboards',
    createNew: 'Create Dashboard',
    empty: 'No dashboards yet',
    emptySubtitle: 'Create your first dashboard to get started.',
    deleteConfirm: 'Are you sure you want to delete this dashboard?',
    dismiss: 'Dismiss',
    noDescription: 'No description',
    widgets: '{count} widgets',
    autoGenerated: 'Auto-generated',
  },
};

function Wrapper({ children }: { children: React.ReactNode }) {
  return (
    <NextIntlClientProvider locale="en" messages={messages}>
      {children}
    </NextIntlClientProvider>
  );
}

// Dynamic import to ensure mocks are applied
let DashboardsPage: React.ComponentType;

beforeAll(async () => {
  const mod = await import('@/app/[locale]/(app)/dashboards/page');
  DashboardsPage = mod.default;
});

describe('DashboardsPage', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('renders loading state', () => {
    mockUseDashboards.mockReturnValue({
      data: [],
      loading: true,
      error: null,
      clone: jest.fn(),
      remove: jest.fn(),
    });

    render(<DashboardsPage />, { wrapper: Wrapper });

    expect(screen.getByTestId('loader')).toBeTruthy();
  });

  it('renders empty state when no dashboards', () => {
    mockUseDashboards.mockReturnValue({
      data: [],
      loading: false,
      error: null,
      clone: jest.fn(),
      remove: jest.fn(),
    });

    render(<DashboardsPage />, { wrapper: Wrapper });

    expect(screen.getByText('No dashboards yet')).toBeTruthy();
    expect(screen.getByText('Create your first dashboard to get started.')).toBeTruthy();
  });

  it('renders dashboard cards', () => {
    mockUseDashboards.mockReturnValue({
      data: [
        {
          id: 'dash-1',
          name: 'Revenue Overview',
          description: 'Monthly revenue metrics',
          is_auto_generated: false,
          created_at: '2026-01-15T00:00:00Z',
          widgets: [{ id: 'w1' }, { id: 'w2' }],
        },
        {
          id: 'dash-2',
          name: 'User Analytics',
          description: null,
          is_auto_generated: true,
          created_at: '2026-01-20T00:00:00Z',
          widgets: [],
        },
      ],
      loading: false,
      error: null,
      clone: jest.fn(),
      remove: jest.fn(),
    });

    render(<DashboardsPage />, { wrapper: Wrapper });

    expect(screen.getByText('Revenue Overview')).toBeTruthy();
    expect(screen.getByText('User Analytics')).toBeTruthy();
    expect(screen.getByText('Monthly revenue metrics')).toBeTruthy();
    expect(screen.getByText('Auto-generated')).toBeTruthy();
  });

  it('renders page title', () => {
    mockUseDashboards.mockReturnValue({
      data: [],
      loading: false,
      error: null,
      clone: jest.fn(),
      remove: jest.fn(),
    });

    render(<DashboardsPage />, { wrapper: Wrapper });

    expect(screen.getByText('Dashboards')).toBeTruthy();
  });
});
